name: nav_router
description: flutter The lightest, easiest and most convenient route management!
version: 0.0.7
#author: crazyQ1 <zonggeu@gmail.com>
homepage: https://github.com/fluttercandies/nav_router

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#
#  plugin:
#    androidPackage: com.example.nav_router
#    pluginClass: NavRouterPlugin
